version: "3.9"
services:
  postgres:
    image: postgres:latest
    env_file:
      - ./docker/postgres.env
    restart: unless-stopped
    ports:
     - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ./docker/pgadmin.env
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    depends_on:
      - postgres
# DO NOT REMOVE!!!
#  pongapp:
#    container_name: pongapp
#    build:
#        context: .
#        dockerfile: ./docker/pongApp.Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - pgadmin
#    volumes:
#      - /app
